---
output:
  pdf_document: default
urlcolor: blue
editor_options: 
  markdown: 
    wrap: sentence
---

<!--HOW TO COMPLETE THIS FORM:-->

```{=html}
<!--
1. Checkboxes in this document appear as follows: 

- [ ] This is a checkbox 

To check a checkbox, replace [ ] by [x], as follows: 

- [x] This is a checked checkbox 

Note that older versions of RStudio (versions lower than 1.3) may not create a formatted checkbox but will leave the original characters, i.e., literally "[ ]" or "[x]". It's fine to submit a PDF in this form.
 
2. For text answers, simply type the relevant text in the areas indicated. A blank line starts a new paragraph. 
 
3. Comments (like these instructions) provide additional instructions throughout the form. There is no need to remove them; they will not appear in the compiled document. 

4. If you are comfortable with Markdown syntax, you may choose to include any Markdown-compliant formatting in the form. For example, you may wish to include R code chunks and compile this document in R Markdown.
-->
```

This form documents the artifacts associated with the article (i.e., the data and code supporting the computational findings) and describes how to reproduce the findings.

# Part 1: Data

-   [ ] This paper does not involve analysis of external data (i.e., no data are used or the only data are generated by the authors via simulation in their code).

```{=html}
<!--
If box above is checked and if no simulated/synthetic data files are provided by the authors, please skip directly to the Code section. Otherwise, continue.
-->
```

-   [x] I certify that the author(s) of the manuscript have legitimate access to and permission to use the data used in this manuscript.

<!-- If data are simulated using random number generation, please be sure to set the random number seed in the code you provide -->

## Abstract

```{=html}
<!--
Provide a short (< 100 words), high-level description of the data
-->
```

We consider both simulation and real data sets.
The simulation studies include continuous, count, and classification responses generated on 2-D U-shaped and 3-D torus domains, as well as Euclidean settings based on the Friedman function involving only unstructured features.
The real data analyses involve spatial and network-structured data sets with diverse response types, including income, housing prices, voting behavior, cancer incidence counts, and binary indicators of air quality and flooding, using geographic coordinates or county adjacency graphs as structured features alongside numerical covariates.

## Availability

-   [x] Data **are** publicly available.
-   [ ] Data **cannot be made** publicly available.

If the data are publicly available, see the *Publicly available data* section.
Otherwise, see the *Non-publicly available data* section, below.

### Publicly available data

-   [ ] Data are available online at:

-   [x] Data are available as part of the paper’s supplementary material.

-   [ ] Data are publicly available by request, following the process described here:

-   [ ] Data are or will be made available through some other mechanism, described here:

<!-- If data are available by request to the authors or some other data owner, please make sure to explain the process of requesting access to the data. -->

### Non-publicly available data

```{=html}
<!--
The Journal of the American Statistical Association requires authors to make data accompanying their papers available to the scientific community except in cases where: 1) public sharing of data would be impossible, 2) suitable synthetic data are provided which allow the main analyses to be replicated (recognizing that results may differ from the "real" data analyses), and 3) the scientific value of the results and methods outweigh the lack of reproducibility.

Please discuss the lack of publicly available data. For example:
-   why data sharing is not possible,
-   what synthetic data are provided, and 
-   why the value of the paper's scientific contribution outweighs the lack of reproducibility.
-->
```

## Description

### File format(s)

```{=html}
<!--
Check all that apply
-->
```

-   [x] CSV or other plain text.
-   [x] Software-specific binary format (.Rda, Python pickle, etc.): .RData
-   [ ] Standardized binary format (e.g., netCDF, HDF5, etc.):
-   [ ] Other (please specify):

### Data dictionary

```{=html}
<!--
A data dictionary provides information that allows users to understand the meaning, format, and use of the data.
-->
```

-   [x] Provided by authors in the following file(s): `data/README.md`
-   [ ] Data file(s) is(are) self-describing (e.g., netCDF files)
-   [ ] Available at the following URL:

### Additional Information (optional)

```{=html}
<!-- 
OPTIONAL: Provide any additional details that would be helpful in understanding the data. If relevant, please provide unique identifier/DOI/version information and/or license/terms of use.
-->
```

# Part 2: Code

## Abstract

The model implementation and data analysis in the paper were done in R and C++.
The `R/` folder provides code for 1) demonstrating the generation of GS-BART input data under different data settings ,2) fitting GS-BART to simulation and real data using Informed Importance Tempering (IIT) method, 3) Bayesian predictive inference of GS-BART, and 4) reproducing key figures and tables in the paper.

```{=html}
<!--
Provide a short (< 100 words), high-level description of the code. If necessary, more details can be provided in files that accompany the code. If no code is provided, please state this and say why (e.g., if the paper contains no computational work).
-->
```

## Description

### Code format(s)

```{=html}
<!--
Check all that apply
-->
```

-   [x] Script files
    -   [x] R
    -   [ ] Python
    -   [ ] Matlab
    -   [ ] Other:
-   [x] Package
    -   [x] R
    -   [ ] Python
    -   [ ] MATLAB toolbox
    -   [ ] Other:
-   [x] Reproducible report
    -   [x] R Markdown
    -   [ ] Jupyter notebook
    -   [ ] Other:
-   [ ] Shell script
-   [ ] Other (please specify):

### Supporting software requirements

#### Version of primary software used

R version 4.4.1.

```{=html}
<!--
(e.g., R version 3.6.0)
-->
```

#### Libraries and dependencies used by the code

Required R packages and their version numbers are listed in `dependencies.txt`.

GS-BART and Generalized GS-BART are implemented in R and C++.
The R package source code is provided in the `R packages/` directory.

```{=html}
<!--
Include version numbers (e.g., version numbers for any R or Python packages used)
-->
```

### Supporting system/hardware requirements (optional)

```{=html}
<!--
OPTIONAL: System/hardware requirements including operating system with version number, access to cluster, GPUs, etc.
-->
```

### Parallelization used

-   [ ] No parallel code used
-   [x] Multi-core parallelization on a single machine/node
    -   Number of cores used:
-   [ ] Multi-machine/multi-node parallelization
    -   Number of nodes and cores used:

### License

-   [x] MIT License (default)
-   [ ] BSD
-   [ ] GPL v3.0
-   [ ] Creative Commons
-   [ ] Other: (please specify)

### Additional information (optional)

The code provided in this repository consists of a main R Markdown file `reproduce.Rmd`, which calls R scripts in `R/` to reproduce key results in the paper.

The R code in `R/` is organized as follows:

-   Code for simulation studies:

    -   `sim_continuous_fit_model.R`: Implements the GS-BART model for continuous-response simulation data.

    -   `sim_count_fit_model.R`: Implements the GS-BART model for count-response simulation data.

    -   `sim_classification_fit_model.R`: Implements the GS-BART model for classification simulation data.

    -   `GSBART_sim_results.R`: Reproduces the key figures and tables from the simulation studies.

-   Code for real data analysis:

    -   `real_continuous_fit_model.R`: Implements the GS-BART model for continuous-response real data.

    -   `real_count_fit_model.R`: Implements the GS-BART model for count-response real data.

    -   `real_classification_fit_model.R`: Implements the GS-BART model for classification real data.

    -   `GSBART_real_results.R`: Reproduces the key figures and tables from the real data analysis.

-   Generation of GS-BART Input Data:

    -   `graph_gen_fun.R`: Provides functions for generating GS-BART input data.

    -   `graph_gen_demo.R`: Demonstrates how to generate GS-BART input data under different data settings.

```{=html}
<!--
OPTIONAL: By default, submitted code will be published on the JASA GitHub repository (http://github.com/JASA-ACS) as well as in the supplementary material. Authors are encouraged to also make their code available in a public code repository, such as on GitHub, GitLab, or BitBucket. If relevant, please provide unique identifier/DOI/version information (e.g., a Git commit ID, branch, release, or tag). If the code and workflow are provided together, this section may be omitted, with information provided in the "Location" section below.
-->
```

# Part 3: Reproducibility workflow

```{=html}
<!--
The materials provided should provide a straightforward way for reviewers and readers to reproduce analyses with as few steps as possible. 
-->
```

## Scope

The provided workflow reproduces:

-   [ ] Any numbers provided in text in the paper
-   [ ] The computational method(s) presented in the paper (i.e., code is provided that implements the method(s))
-   [ ] All tables and figures in the paper
-   [x] Selected tables and figures in the paper, as explained and justified below: This workflow reproduces all tables and figures related to GS-BART in the key sections of the paper, including 1) Section 5 (Simulation Studies and Real Data Analysis), and 2) Sections S4.2 of the Supplementary Material, which provide supplementary results to Sections 5, respectively.

## Workflow

### Location

The workflow is available:

```{=html}
<!--
Check all that apply, and in the case of a Git repository include unique identifier, such as specific commit ID, branch, release, or tag.
-->
```

-   [x] As part of the paper’s supplementary material.
-   [ ] In this Git repository:
-   [ ] Other (please specify):

```{=html}
<!--
Indicate where the materials (generally including the code, unless in a separate location and indicated in the previous section) are available. We strongly encourage authors to place their materials (but not large datasets) in a Git repository hosted on a site such as GitHub, GitLab, or BitBucket. If the repository is private during the review process, please indicate the location where it will be available publicly upon publication, and also include the materials as a zip file (e.g., obtained directly from the Git hosting site) as supplementary materials.
-->
```

### Format(s)

```{=html}
<!--
Check all that apply
-->
```

-   [ ] Single master code file
-   [ ] Wrapper (shell) script(s)
-   [x] Self-contained R Markdown file, Jupyter notebook, or other literate programming approach
-   [ ] Text file (e.g., a readme-style file) that documents workflow
-   [ ] Makefile
-   [ ] Other (more detail in *Instructions* below)

### Instructions

## Instructions for use

All workflow information to reproduce key results of the paper is contained in `reproduce.Rmd`.
The steps for running the workflow are:

**Step 1**: Install all required R packages in `dependencies.txt`.

**Step 2** (Optional): Compile the source code for the GS-BART library by running the following command in your R Console:

```         
install.packages('R packages/GSBart_0.0.1.tar.gz', type = "source", repo = NULL) 
install.packages('R packages/G2SBart_0.0.1.tar.gz', type = "source", repo = NULL)
```

This step is optional and only required if you want to re-run GS-BART model fitting and prediction.

**Step 3** (Optional): Modify the options in Line 19-25 of `reproduce.Rmd` accordingly.
By default, key figures and tables are reproduced from pre-computed model outputs in `data/`.
To re-generate model outputs, make the following change(s):

-   To re-run GS-BART model in continuous-response simulation data, set `sim_continuous_fit = TRUE`.

-   To re-run GS-BART model in count-response simulation data, set `sim_count_fit = TRUE`.

-   To re-run GS-BART model in classification simulation data, set `sim_classification_fit = TRUE`.

-   To re-run GS-BART model in continuous-response real data, set `real_continuous_fit = TRUE`.

-   To re-run GS-BART model in count-response real data, set `real_count_fit = TRUE`.

-   To re-run GS-BART model in classification real data, set `real_classification_fit = TRUE`.

**Step 4**: Run the workflow in `reproduce.Rmd` by compiling the R Markdown file.
For example, this can be done by running the following command in your terminal:

```         
Rscript -e "rmarkdown::render('reproduce.Rmd')"
```

Reproducible results can be found in the generated `reproduce.html` file.

```{=html}
<!--
Describe how to use the materials provided to reproduce analyses in the manuscript. Additional details can be provided in file(s) accompanying the reproducibility materials. If no workflow is provided, please state this and say why (e.g., if the paper contains no computational work).
-->
```

### Expected run-time

Approximate time needed to reproduce the analyses on a standard desktop machine:

-   [ ] \< 1 minute
-   [ ] 1-10 minutes
-   [ ] 10-60 minutes
-   [x] 1-8 hours
-   [ ] \> 8 hours
-   [ ] Not feasible to run on a desktop machine, as described here:

### Additional information (optional)

```{=html}
<!--
OPTIONAL: Additional documentation provided (e.g., R package vignettes, demos or other examples) that show how to use the provided code/software in other settings.
-->
```

# Notes (optional)

```{=html}
<!--
OPTIONAL: Any other relevant information not covered on this form. If reproducibility materials are not publicly available at the time of submission, please provide information here on how the reviewers can view the materials.
-->
```
