rm(list=ls())
library(ggplot2)
library(ggpubr)
load('~/Downloads/code/test_code/Election.Rdata')
load("/Users/shurenhe/Downloads/GSBart_rebuttal/Election/Electionres.Rdata")
Unstandardize = function(x, std_par){ return(x * std_par['scale'] + std_par['mean']) }
GSB.pred.unstandardized = Unstandardize(colMeans(Electionres$phi.test), stdY$std_par)
GSBart_MSPE = mean((GSB.pred.unstandardized - y.test.unstandardized)^2)
GSBart_MAPE = mean(abs(GSB.pred.unstandardized - y.test.unstandardized))

MSPE_trace <- colMeans((Y - t(Electionres$phi.train))^2)
pdf(file = "/Users/shurenhe/Downloads/GSBart_rebuttal/Election/Election_traceplot.pdf", width  = 15, height = 7)
plot(MSPE_trace, ylab = "MSPE", xlab = "Iteration", type = 'l', main = "Trace plot for Election")
abline(v = 50, lty = 2, lwd = 2, col = 'red')
# text(50, 0.0002, "Initial", cex = 1.5)
# text(650, 0.0002, "Burn-in", cex = 1.5)
abline(v = 750, lty = 2, lwd = 2, col = 'blue')
# text(1700, 0.0002, "After burn-in", cex = 1.5)
dev.off()
